version: '3.8'
services:
  postgres_server:
    image: postgres:16.0
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/config/realm-export.json # Se hai un file di importazione del realm
    ports:
      - 9080:9080
    volumes:
      - ./config:/opt/keycloak/data/import
    command: start-dev

volumes:
  postgres-data:

networks:
  adminer-network: