version: '3.8'

services:
  postgres_server:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-catdb}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8088
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - backend-network
    restart: unless-stopped
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /config/realm-export.json
    ports:
      - 9080:8080
    volumes:
      - ./config:/opt/keycloak/data/import
    command: start-dev
    depends_on:
      - postgres_server
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  backend-network:
