version: '3.8'
services:
  postgres_server:
    image: postgres:16.0
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network

volumes:
  postgres-data:

networks:
  adminer-network: