version: '3.8'

services:
  postgres_server:
    image: postgres:16.0
    environment:
      POSTGRES_DB: catdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network

  cat-board-be:
    image: anzaldiemanuele/cat-board-be:latest
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres_server:5432/catdb
      POSTGRES_HOST: postgres_server
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: catdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - postgres_server
    networks:
      - adminer-network

volumes:
  postgres-data:

networks:
  adminer-network:
